image: mcr.microsoft.com/dotnet/sdk:7.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build --configuration Release --no-restore
          - dotnet test --no-build --verbosity normal
    - step:
        name: Publish
        script:
          - dotnet publish -c Release -o publish
        artifacts:
          - publish/**
    - step:
        name: Deploy to Production
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              LOCAL_PATH: 'publish/wwwroot'
              ACL: 'public-read'
              DELETE_FLAG: 'true' 