name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: Display directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        
    - name: Restore dependencies
      working-directory: ./BlazorApp1
      run: dotnet restore
      
    - name: Build
      working-directory: ./BlazorApp1
      run: dotnet build --configuration Release --no-restore
      
    - name: Publish
      working-directory: ./BlazorApp1
      run: dotnet publish Client/BlazorApp1.Client.csproj -c Release -o ../release --nologo
      
    - name: List published files
      run: |
        echo "Checking release directory..."
        ls -la release || echo "Release directory not found"
        echo "Checking for wwwroot..."
        ls -la release/wwwroot || echo "wwwroot directory not found"
        
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/RPVMS\/" \/>/g' release/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: release/wwwroot

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}
        artifact_name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 